# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1
workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
          matrix:
            parameters:
              python_version: ["2.7", "3.5"]
              django_version: ["django111", "django22"]
            exclude:
              - python_version: "2.7"
                django_version: "django22"
jobs:
  test:
    parameters:
      django_version:
        type: string
      python_version:
        type: string
      debian_version:
        type: string
        default: stretch
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:<< parameters.python_version >>-<< parameters.debian_version >>

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo<< parameters.python_version >>

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-<< parameters.python_version >>-<< parameters.django_version >>-dependencies-{{ checksum "requirements/test.txt" }}
      - run:
          name: Install dependencies.
          command: |
            test -d venv || virtualenv venv
            . venv/bin/activate
            pip install -r requirements/tox.txt

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            export TOXENV=${TOX_ENV//./}
            make run-tests

      - save_cache:
          paths:
            - ./.tox
            - ./node_modules
          key: v2-<< parameters.python_version >>-<< parameters.django_version >>-dependencies-{{ checksum "requirements/test.txt" }}

    environment:
      - TOX_ENV: py<< parameters.python_version >>-<< parameters.django_version >>
