# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-28 15:51
from __future__ import unicode_literals

import uuid

from django.db import migrations, models

import eox_hooks.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HookExecutionAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                 verbose_name=b'Public identifier')),
                ('status', models.PositiveIntegerField(choices=[(0, b'FAIL'), (1, b'SUCCESS')],
                 default=eox_hooks.constants.Status(1), editable=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('hook_name', models.CharField(max_length=150)),
                ('task_name', models.CharField(max_length=150)),
                ('tenant_domain', models.CharField(max_length=150)),
                ('task_duration', models.FloatField(null=True)),
            ],
        ),
    ]
