# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 00:49
from __future__ import unicode_literals

import uuid

from django.db import migrations, models

import eox_hooks.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HookExecutionAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                         verbose_name=b'Public identifier')),
                ('status', models.PositiveIntegerField(choices=[(0, b'FAIL'), (1, b'SUCCESS')],
                                                       default=eox_hooks.constants.Status(1))),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_event', models.CharField(max_length=150)),
                ('action_name', models.CharField(max_length=150)),
                ('log_message', models.TextField(blank=True, null=True)),
                ('tenant_domain', models.CharField(max_length=150)),
                ('action_duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
